# Remova a linha "version: '3.8'" (está obsoleta)

services:
  postgres:
    image: postgres:15-alpine
    container_name: receita_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  etl_app:
    build:
      context: .
      dockerfile: Dockerfile  # Use Dockerfile simples em vez de Dockerfile.cron
    container_name: receita_etl
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./etl:/app/etl
    networks:
      - etl_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    command: ["tail", "-f", "/dev/null"]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: receita_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGLADMIN_EMAIL}
      PGLADMIN_DEFAULT_PASSWORD: ${PGLADMIN_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - etl_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  etl_network:
    driver: bridge
