
services:
  postgres:
    image: postgres:15-alpine
    container_name: receita_postgres
    environment:
      POSTGRES_DB: receita_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
